config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  resources :lectures do
    resources :comments
  end
  resources :lectures do
    member do
      put "like" => "lectures#upvote"
      put "unlike" => "lectures#downvote"
    end
  end
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }  # The priority is based upon order of creation: first created -> highest priority.

  root 'courses#index'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :comments,:dependent=>:delete_all
  mount_uploader :attachment, FileUploader
  acts_as_votable
  validates :title , :presence=>true
  validates :content , :presence=>true
  validates :attachment , :presence=>true





end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :authenticate_user!,only: [:upvote, :downvote]
  # before_action :find_lect,only: [:edit]
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id = current_user.id


    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'course was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end


  end
  # def edit
  #   if current_user.id != @lecture.user_id
  #   redirect_to courses_path
  #   end
  # end
  def upvote
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_from current_user
    redirect_to lecture_path
  end

  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_from current_user
    redirect_to lecture_path
  end
  private
    # def find_lect
    #   @lecture=Lecture.find(params[@lecture.id])
    # end
    def lecture_params
      params.require(:lecture).permit(:title, :content, :attachment, :user_id, :course_id)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.collection_select :course_id, current_user.courses,:id,:title, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<%if current_user.id == @lecture.user_id%>
  <%= render 'form' %>

  <%= link_to 'Show', @lecture %>
  <%= link_to 'Back', lectures_path %>

<%end%>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div style="box-shadow: 10px 10px 5px #888888" class="jumbotron">
    <h1 align="center"> Listing Lectures</h1>
  </div>
</div>

<table class=" table table-responsive table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Attachment</th>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.title %></td>
        <td><a href="<%= lecture.attachment_url %>" download>Download Lecture</a></td>
        <td><%= lecture.user.name %></td>
        <td><%= lecture.course.title %></td>
        <td><a class="btn btn-success" style="text-decoration: none"  href="/lectures/<%=lecture.id%>"> Show </a></td>
        <%if current_user.id == lecture.user_id%>
        <td><a class="btn btn-warning" style="text-decoration: none"  href="/lectures/<%=lecture.id%>/edit"> Edit </a></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger" %></td>
         <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if (current_user.role == "instructor") %>
<div align="center">
  <a class="btn btn-primary" style="text-decoration: none" href="/lectures/new">Add Lecture</a>
</div>
<%end%>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="jumbotron">
    <h2 align="center"><%=@lecture.title%></h2>
  <div align="center">
    <strong>Created By:</strong>
    <%= @lecture.user.name %>
    <strong>Course:</strong>
    <%= @lecture.course.title %>
  </div>
    <p><%=raw @lecture.content%></p>

    <div align="right">
      <a href="<%= @lecture.attachment_url %>" download><h4>Download Lecture</h4></a>
    </div>
  </div>
  <div class="text-align:center;" align="center">
    <%= link_to like_lecture_path(@lecture), class:"like" , method: :put do %>
        <button type="button" class="btn btn-info" aria-label="Left Align">

          <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center " aria-hidden="true"> </span>
          <span class="bage"><%= @lecture.get_upvotes.size %></span>
        </button>

    <% end  %>


    <%= link_to unlike_lecture_path(@lecture), class:"like" , method: :put do %>
        <button type="button" class="btn btn-info" aria-label="Left Align">

          <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center " aria-hidden="true"> </span>
          <span class="bage"><%= @lecture.get_downvotes.size %></span>
        </button>

    <% end  %>

  </div>
</div>
<h2 align="center">Comments</h2>
<div id="comments">
  <%= render :partial => @lecture.comments %>
</div>
<%= simple_form_for [@lecture ,Comment.new] do |f| %>
    <p>
      <%= f.input :cont , :lable => "NEW COMMENT" , as: :text , input_html: { row:"3" } %>
    </p>
    <div class="btn">
      <%= f.submit "Add Comment " , class:'btn btn-primary'  %>
    </div>
<% end %>
<div align="center">
<%if current_user.id == @lecture.user_id%>
 <button><%= link_to 'Edit', edit_lecture_path(@lecture) %></button>
  <%end%>
 <button> <%= link_to 'Back', lectures_path %></button>
</div>