config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  resources :lectures do
    resources :comments
  end
  resources :lectures do
    member do
      put "like" => "lectures#upvote"
      put "unlike" => "lectures#downvote"
    end
  end
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }  # The priority is based upon order of creation: first created -> highest priority.

  root 'courses#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lecture
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :lect
  def create
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @lecture
    else
      flash.now[:danger] = "error"
    end
  end



  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to lecture_path(@comment.lecture_id), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def lect
      @lecture=Lecture.find(params[:lecture_id])
    end
    def comment_params
      params.require(:comment).permit(:cont, :user_id, :lecture_id)
    end
    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do  %>

    <p>
      <strong>
        Posted <%= time_ago_in_words(comment.created_at) %>
      </strong><br>
      <%= h(comment.cont) %>
      <% if current_user.id ==  comment.user_id %>
          <%= link_to 'Edit', edit_lecture_comment_path(comment.lecture,comment),class:"btn btn-primary" %> |
          <%= link_to 'Delete', lecture_comment_path(comment.lecture,comment), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %>
      <% end %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@lecture,@lecture.comments.build] do |f| %>

  <div class="field">
    <%= f.label :cont %><br>
    <%= f.text_area :cont %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', lecture_path(@comment.lecture) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Cont</th>
      <th>User</th>
      <th>Lecture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.cont %></td>
        <td><%= comment.user %></td>
        <td><%= comment.lecture %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cont:</strong>
  <%= @comment.cont %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Lecture:</strong>
  <%= @comment.lecture %>
</p>

<%= link_to 'Edit', edit_lecture_comment_path(@comment.lecture,@comment.id) %> |
<%= link_to 'Back', lectures_path %>